// systemd --user lifecycle for the brain daemon: `codesema brain
// install-service` writes ~/.config/systemd/user/codesema-brain.service from
// the unit shipped at assets/systemd/codesema-brain.service — the asset is
// resolved the same way serve.ts resolves its embedded `web-dist` (a URL
// relative to this module's own bundled location) — then pins
// WorkingDirectory/ExecStart to the repo and binary actually running this
// command and enables the unit now. `uninstall-service` reverses it.
//
// Only the three per-install directives (WorkingDirectory, EnvironmentFile,
// ExecStart) are computed here; every other line (Description, After,
// Restart policy, …) is read back out of the shipped template so the
// generated unit never drifts from the one documented in that file.
//
// Logic only, no console output: brain-commands.ts renders the result, the
// same split brain-draft.ts's draftAndPublishTicket has with its own caller.

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { t } from './i18n.js'

const UNIT_TEMPLATE_PATH = fileURLToPath(
  new URL('../assets/systemd/codesema-brain.service', import.meta.url),
)

const UNIT_NAME = 'codesema-brain.service'

/** The one `execFileSync` shape actually needed here, pulled out as its own type for the same reason brain-commands.ts's `SpawnFn` is: a test fake has no reason to satisfy the real dozen-overload signature. */
export type ExecCommandFn = (command: string, args: readonly string[]) => string

function realExec(command: string, args: readonly string[]): string {
  return execFileSync(command, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
}

function isNotFound(err: unknown): boolean {
  return (err as NodeJS.ErrnoException | null)?.code === 'ENOENT'
}

function systemdUserDir(): string {
  const base = process.env.XDG_CONFIG_HOME || join(homedir(), '.config')
  return join(base, 'systemd', 'user')
}

export function systemdUnitPath(): string {
  return join(systemdUserDir(), UNIT_NAME)
}

/**
 * Directive lines only, keyed by name: comments, section headers and blank
 * lines are dropped. The three per-install directives are looked up here too
 * (WorkingDirectory, ExecStart) but the caller always overrides them —
 * parsing them regardless keeps this function ignorant of which keys are
 * "static" vs "computed", one less thing to keep in sync by hand.
 */
function parseUnitDirectives(templateText: string): Map<string, string> {
  const directives = new Map<string, string>()
  for (const line of templateText.split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '' || trimmed.startsWith('#') || trimmed.startsWith('[')) {
      continue
    }
    const eq = trimmed.indexOf('=')
    if (eq === -1) {
      continue
    }
    directives.set(trimmed.slice(0, eq).trim(), trimmed.slice(eq + 1))
  }
  return directives
}

export function renderBrainServiceUnit(input: {
  workingDirectory: string
  execStart: string
  environmentFile: string | null
}): string {
  const directives = parseUnitDirectives(readFileSync(UNIT_TEMPLATE_PATH, 'utf8'))
  const get = (key: string, fallback: string): string => directives.get(key) ?? fallback
  const lines = [
    '# Generated by `codesema brain install-service`; re-run that command after',
    '# upgrading codesema instead of hand-editing ExecStart below. Stop with',
    '# `systemctl --user stop codesema-brain.service`, never a raw `kill` or',
    '# `codesema brain stop`: Restart=on-failure relaunches either.',
    '',
    '[Unit]',
    `Description=${get('Description', 'codesema brain daemon')}`,
    `After=${get('After', 'network-online.target')}`,
    `Wants=${get('Wants', 'network-online.target')}`,
    '',
    '[Service]',
    `Type=${get('Type', 'simple')}`,
    `WorkingDirectory=${input.workingDirectory}`,
    ...(input.environmentFile ? [`EnvironmentFile=${input.environmentFile}`] : []),
    `ExecStart=${input.execStart}`,
    `Restart=${get('Restart', 'on-failure')}`,
    `RestartSec=${get('RestartSec', '5')}`,
    '',
    '[Install]',
    `WantedBy=${get('WantedBy', 'default.target')}`,
    '',
  ]
  return lines.join('\n')
}

function ensureSystemctlAvailable(execFn: ExecCommandFn): void {
  try {
    execFn('systemctl', ['--version'])
  } catch (err) {
    if (isNotFound(err)) {
      throw new Error(t('brain.systemctlNotFound'), { cause: err })
    }
    throw err
  }
}

/** `process.argv[1]`, realpath'd through any symlink/shim — never a bare `codesema` PATH lookup, which a systemd --user unit is not guaranteed to resolve the same way an interactive shell does. */
function resolveExecStart(): string {
  const entry = process.argv[1]
  if (entry === undefined) {
    throw new Error(t('brain.serviceExecPathUnknown'))
  }
  return realpathSync(entry)
}

export type InstallBrainServiceOptions = {
  workingDirectory: string
  /** Resolves a relative `envFile` — the CLI's own invocation directory, threaded through explicitly rather than read from `process.cwd()` here so this stays a function of its inputs. */
  cwd: string
  envFile?: string | undefined
  execFn?: ExecCommandFn | undefined
}

export type InstallBrainServiceResult = {
  unitPath: string
  workingDirectory: string
  execStart: string
  environmentFile: string | null
  /** Set when `loginctl enable-linger` failed (containers/WSL commonly have no session bus): the unit is still installed and enabled, it just will not survive past the invoking user's session ending. */
  lingerError: string | null
}

export function installBrainService(opts: InstallBrainServiceOptions): InstallBrainServiceResult {
  const execFn = opts.execFn ?? realExec
  // Probed before anything is written: a missing systemd must leave no
  // half-installed unit file behind.
  ensureSystemctlAvailable(execFn)

  const environmentFile = opts.envFile ? resolve(opts.cwd, opts.envFile) : null
  if (environmentFile && !existsSync(environmentFile)) {
    throw new Error(t('brain.envFileNotFound', { path: environmentFile }))
  }

  const execStart = `${resolveExecStart()} brain serve`
  const unitPath = systemdUnitPath()
  mkdirSync(dirname(unitPath), { recursive: true })
  writeFileSync(
    unitPath,
    renderBrainServiceUnit({ workingDirectory: opts.workingDirectory, execStart, environmentFile }),
  )

  execFn('systemctl', ['--user', 'daemon-reload'])
  execFn('systemctl', ['--user', 'enable', '--now', UNIT_NAME])

  let lingerError: string | null = null
  try {
    // No USER argument: `loginctl enable-linger` defaults to the caller's own
    // session, which is exactly the account this unit was just installed for.
    execFn('loginctl', ['enable-linger'])
  } catch (err) {
    lingerError = err instanceof Error ? err.message : String(err)
  }

  return {
    unitPath,
    workingDirectory: opts.workingDirectory,
    execStart,
    environmentFile,
    lingerError,
  }
}

export type UninstallBrainServiceResult = { removed: boolean; unitPath: string }

export function uninstallBrainService(opts: {
  execFn?: ExecCommandFn | undefined
}): UninstallBrainServiceResult {
  const execFn = opts.execFn ?? realExec
  const unitPath = systemdUnitPath()
  if (!existsSync(unitPath)) {
    return { removed: false, unitPath }
  }
  ensureSystemctlAvailable(execFn)
  execFn('systemctl', ['--user', 'disable', '--now', UNIT_NAME])
  rmSync(unitPath)
  execFn('systemctl', ['--user', 'daemon-reload'])
  return { removed: true, unitPath }
}
